#
# ~/.bashrc
#

# enable starship
eval "$(starship init bash)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias vim=nvim
alias mutt=neomutt
# remove files interactively
alias rm='rm -i'

# add cargo and rust stuff to path
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

# vim mode + jk changes to normal mode 
bind '"jk":vi-movement-mode'
set -o vi

# purge mail
alias purgemail='notmuch search --output=files tag:deleted | xargs -l rm'

# fuzzy find

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
