#
# ~/.bash_profile
#

# startx in login
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
startx
fi

HISTIGNORE='ll*:la*:cd*:ls:clear:mutt'

[[ -f ~/.bashrc ]] && . ~/.bashrc
. "$HOME/.cargo/env"

# add doom binary to PATH
PATH=$PATH:$HOME/.emacs.d/bin
