#
# ~/.bashrc
#

# enable starship
eval "$(starship init bash)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias vim=nvim
alias mutt=neomutt
# remove files interactively
alias rm='rm -i'

# add cargo and rust stuff to path
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

# purge mail
alias purgemail='notmuch search --output=files tag:deleted | xargs -l rm'
