#! /bin/sh

# auto run

# HiDPI
export GDK_DPI_SCALE=1.5
export QT_SCALE_FACTOR=1.5

# set trackpad to clickfinger (context click is two finger)
# "Elan Touchpad"
# "PIXA3854:00 093A:0274 Touchpad"
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" "libinput Click Method Enabled" 0 1
sxhkd &
nitrogen --restore &
picom --config /home/yasushi/.config/picom/picom.conf &
ulauncher --hide-window --no-window-shadow &
blueman-tray &

/home/yasushi/.config/polybar/launch.sh

# monitor control
bspc monitor eDP1 -d 1 2 3
bspc monitor HDMI2 -d 4 5 6

# other configs
bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config focused_border_color "#EBCB8B"
bspc config normal_border_color "#D8DEE9"
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config -m HDMI2 bottom_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off
bspc rule -a Emacs state=tiled 
